# 本地测试暂时不指定端口
# server:
#  port: 18081

name: main-web-server

spring:
  cloud:
    sentinel:
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: local-test
            group-id: sentinel:config
            data-id: ${spring.application.name}-sentinel-rule
            data-type: json
            rule-type: flow