# test
user:
  name: order-server-name
  age: 300


spring:
  cloud:
    sentinel:
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: local-test-2
            group-id: sentinel:config
            data-id: ${spring.application.name}-sentinel-rule
            data-type: json
            rule-type: flow